### ISSUE TITLE
Possible accuracy issues.

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [RemeaMiku/LXNaviPDR#3]
I think we have some problem with the measurements,
Scenario: If I'm on a bike, the measurements fail and it doesn't register on the map correctly.
Another scenario: walking seems to work well or better, without errors.

I'm not sure if it's a problem with the country (Brazil) or not, I'm still investigating the problem further.

**Comment by RemeaMiku** [comment]
Well, the app uses a simple PDR algorithm. PDR stands for Pedestrian Dead Reckoning, which only applies to pedestrians, not cyclists.

**Comment by andersonvieiragomeslopes** [comment]
> Well, the app uses a simple PDR algorithm. PDR stands for Pedestrian Dead Reckoning, which only applies to pedestrians, not cyclists.

In this case it makes sense that it doesn't work with bikes, do you have any ideas how you could make this work with bikes?

**Comment by RemeaMiku** [comment]
Unfortunately, no. This is the term project of a course about indoor positioning technology, since indoor cycling is usually not possible, the research on the positioning of cyclists is beyond the scope of the course. The GNSS(Global Navigation Satellite System) signal is usually weak indoors, so the PDR algorithm mainly relies on accelerometers, gyroscopes and magnetometers. If you are on a bike, using GNSS directly is much better.

In fact, the PDR algorithm itself has many limitations. It assumes that the pedestrian's phone is being held forward smoothly. The pace is then detected by the pattern of changes in the sensor output. For the cycling scenario, I don't know how to do this.

**Comment by andersonvieiragomeslopes** [comment]
> Unfortunately, no. This is the term project of a course about indoor positioning technology, since indoor cycling is usually not possible, the research on the positioning of cyclists is beyond the scope of the course. The GNSS(Global Navigation Satellite System) signal is usually weak indoors, so the PDR algorithm mainly relies on accelerometers, gyroscopes and magnetometers. If you are on a bike, using GNSS directly is much better.
> 
> In fact, the PDR algorithm itself has many limitations. It assumes that the pedestrian's phone is being held forward smoothly. The pace is then detected by the pattern of changes in the sensor output. For the cycling scenario, I don't know how to do this.

Thanks for the explanation, I think I'm starting to understand your project better.
If you are interested in improving the project even further, I would like to be part of it and contribute more PR, there is still a lot to improve, background services (which I have already done) and other things.
Thank you for everything so far.

**Comment by RemeaMiku** [comment]
I don't think I'll be working on it anymore, but I'm very glad to see someone interested in my project and make it better. I would invite you to be a collaborator on this repository. Just feel free to do it. Thank you for your contributions.
